services:
  # Flink JobManager: The master node
  jobmanager:
    image: flink:1.20.3-java17
    ports:
      - "9091:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./conf:/opt/flink/conf
      - flink_data:/tmp/
    networks:
      - n8n_flink_bridge

  # Flink TaskManager: The worker node
  taskmanager:
    image: flink:1.20.3-java17
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    volumes:
      - ./conf:/opt/flink/conf
      - flink_data:/tmp/
    networks:
      - n8n_flink_bridge

  kafka:     
    image: 'apache/kafka:latest'
    environment:
      # Unique ID for the node within the cluster
      - KAFKA_NODE_ID=0
      # Roles for the process: act as both broker and controller
      - KAFKA_PROCESS_ROLES=broker,controller
      # Define listeners for different types of traffic
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # Map security protocols to listener names
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # Voters for the controller quorum (nodeId@host:port)
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Which listener the controller should use
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # The address clients (like n8n or Flink) use to connect
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      # Required for single-node development setup
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    networks:
      - n8n_flink_bridge

  # n8n Automation Tool
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false  # Set to false if you are NOT using HTTPS/SSL
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_flink_bridge

# Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - DYNAMIC_CONFIG_ENABLED=true
    networks:
      - n8n_flink_bridge

networks:
  n8n_flink_bridge:
    driver: bridge

volumes:
  n8n_data:
  flink_data: